linux/Makefile
source/lib/menu.c

Added linux Makefile

---

rxtools/source/lib/fs.c

TODO
Eval NULL after FindNandCtr

Add extra validation to NAND CTR start and refactor

---

brahma/data/payload/source/main.c
msethax/payload/source/main.c
msethax/rxinstaller/source/main.cpp
rxmode/native_firm/source/arm9/source/myThread/myThread.c
rxtools/source/MainMenu.h
rxtools/source/features/CTRDecryptor.c
rxtools/source/features/NandDumper.c
rxtools/source/features/TitleKeyDecrypt.c
rxtools/source/features/cfw.c
rxtools/source/features/configuration.c
rxtools/source/features/downgradeapp.c
rxtools/source/features/nandtools.c
rxtools/source/features/padgen.c
rxtools/source/lib/console.c
rxtools/source/lib/draw.c
rxtools/source/lib/fatfs/diskio.c
rxtools/source/lib/filepack.c
rxtools/source/lib/hid.c
rxtools/source/lib/i2c.c
rxtools/source/lib/ncch.c
rxtools/source/lib/screenshot.c
tools/toolsrc/cfwtool/main.c
tools/toolsrc/pack_tool/main.c

This one should be merged after previous one. Will change binaries because actual bugs is fixed along with warnings suppression.
upd: Checked on O3DS9.2E - ninjhax, spiderhax, emunand, agb_firm (reverted to non-patched before updating from 2.5.2)

Fixed bugs and typos which produced warnings

---

rxtools/source/lib/console.c
rxtools/source/lib/draw.c
rxtools/source/lib/draw.h
rxtools/source/lib/screenshot.c
rxtools/source/main.c

Get/DrawPixel prototype fixed with pointer type
Functions parameters switched to types defined in common.h
Initial support for soft alpha channel

Draw lib cleanup

---

.gitignore
theme/makebgr-all.bat
theme/makebgr-all.sh
theme/makebgr.sh

Also removed .bat exception and improved on the Linux scripts.

Added a Theme converter, for Windows. Made other minor changes, too.

---

tools/themetool.bat

Fixed the strip PNG function (it had "goto:EOF", at the start of it?),
tidied up the code to save a few bytes, added more detailed error
outputs etc.

Fixed a broken function, minor tidy ups.

---

rxtools/source/features/downgradeapp.c

Fixed Downgrade App Errors/Issues
Proper Button Detection in DG Apps
Added Features to FBI/HS DG/Restore

Downgrade App Updates

---

rxtools/source/features/downgradeapp.c

Added option to only check TMD for first-time installers.
Proper pad input checks, using HID standard functions, instead of custom
input.

FBI Injector Additions, Code Cleanup

---

rxtools/source/main.c

Start and Select buttons do the "unified" operations, keeping it less fragmented as other projects use the same button layout :)

Switched Start and Select functions around.

---

Makefile

Fix https://github.com/roxas75/rxTools/pull/104#discussion_r36044324 .

Makefile: Fix release

---

README.md

Fix #135. (It's not a true fix, of course. It should be fixed later if it's not so difficult.)

README.md: Use 64 bit environment

---

rxtools/source/features/CTRDecryptor.c

That one probably will be the last fix for decryption :+1:

fixed CTR decryption (once again)

---

README.md

Requires a specific version of ImageMagick :)

Doesn't require x64.

---

rxtools/source/lib/draw.c

@AlbertoSONIC no your decision - a bit smoother fade-out effect.
may be even smoother/faster if load image into separate buffer and read source from it instead of framebuffer.

more smooth fade-out

---

brahma/data/payload/source/main.c
rxtools/source/MainMenu.h
rxtools/source/features/configuration.c
rxtools/source/features/configuration.h
rxtools/source/features/screenshot.c

Old screenshot function captures bad image due to some typo and GetPixel are somewhat incorrect.
I didn't look into the GetPixel issue but just stripped use of GetPixel and read VRAM directly.

screenshot improvements and some minor fixes

---

rxinstaller/CakesROPSpider/Makefile
rxinstaller/Makefile

CakesROP made really bad Makefiles so I have to fix it like this for subdirectories...

Makefile fix

---

rxtools/source/features/configuration.c
rxtools/source/features/downgradeapp.c
rxtools/source/features/downgradeapp.h

downgradeapp.c and configuration.c

---

rxtools/source/features/configuration.c

I tested this, It works. Might as well have it read the file here since just about everything else is being loaded from this directory now. :D

Move firmware.bin to rxtools/system

---

rxmode/agb_firm/script.ld
rxmode/twl_firm/script.ld
rxtools/source/features/configuration.c

fixed firm patches

---

.gitmodules
Makefile
README.md
lang/ko.json

I think it is more reasonable to use CakesROP instead of rxinstaller.
This solves Issue #203. Sadly, I have not tested this on new 3ds.

Added CakesROP and update CakeHax

---

rxtools/source/features/downgradeapp.c

Simple way is the best

---

rxtools/source/features/padgen.c

Our dumped movable.sed is placed at sdcard:/rxTools/movable.sed, but SDinfo.dat xorpads gen reads sdcard:/movable.sed.
So read it from nands if movable.sed is missing from sdcard should simplify the whole process.

Read movable.sed from nands if it is not placed on SD

---

README.md

Wobot wobot wobot. Nightly build links :)

Added nightlies :D

---

README.md

He doesn't build them, anymore.

Removed Nastys builds. Bai Bai.

---

rxmode/native_firm/Makefile
rxmode/native_firm/source/p9_emunand_hook_1.S
rxmode/native_firm/source/p9_emunand_hook_2.S
rxmode/native_firm/source/payload/arm11/hookswi.S
rxmode/native_firm/source/payload/arm9/EmuNAND.S
rxmode/native_firm/source/payload/arm9/myThread/FS.s
rxmode/native_firm/source/payload/arm9/myThread/lib.c
rxmode/native_firm/source/payload/arm9/myThread/myThread.c

Tested only on old 3DS 4.5.0 (by updating to 10.1.0 with emuNAND)

Reduce the size of payload

---

rxtools/source/features/configuration.c
rxtools/source/features/firm.c
rxtools/source/features/firm.h

This change is almost same with #244. It depends on #257 and removes FirmInfo completely.
Also this pull request doesn't include changes for rxmode in #244.

Remove FirmInfo

---

rxtools/source/lib/draw.h

This is a quick fix for the latest CakeHax.

Fixed bottom screen issue

---

rxmode/native_firm/Makefile
rxmode/native_firm/source/p9_emunand_hook_1.S
rxmode/native_firm/source/p9_emunand_hook_2.S
rxtools/source/features/TitleKeyDecrypt.c

Fixes #267 and #270

---

lang/fr.json
tools/themetool.bat
tools/themetool.sh

fr.json (correction) + themetool (rev.1)

---

include/reboot.h
rxmode/agb_firm/Makefile
rxmode/agb_firm/script.ld
rxmode/native_firm/source/p9_reboothax_body.c
rxmode/native_firm/source/p9_reboothax_entry.c
rxmode/twl_firm/Makefile
rxmode/twl_firm/script.ld
rxtools/source/features/configuration.c
rxtools/source/features/firm.c
rxtools/source/features/firm.h

Fix AGB and TWL FIRM patches

---

include/reboot.h
rxmode/native_firm/Makefile
rxmode/native_firm/source/include/emunand.h
rxmode/native_firm/source/include/keyx.h
rxmode/native_firm/source/p9_keyx_spoof.s
rxmode/native_firm/source/p9_reboothax_body.c
rxmode/native_firm/source/p9_reboothax_entry.c
rxmode/native_firm/source/payload/arm9/EmuNAND.S
rxmode/native_firm/source/payload/arm9/myThread/myThread.c
rxtools/Makefile
rxtools/source/features/firm.c
rxtools/source/features/reboot.s

Improvements for reboot

---

Makefile
rxmode/Makefile
rxtools/Makefile

See https://github.com/roxas75/rxTools/pull/322#issuecomment-168016150.

Fix `Makefile`s

---

Makefile
rxmode/Makefile

This reverts commit f5096d5ddead1978ca6713087eb6100f524f964f.
\# Conflicts:
\#	Makefile
\#	rxtools/Makefile
See also #322.

Revert "Output files in the same directory"

---

README.md

removed repetition of "## How to install DS Profile (MSET) Exploit (requires MSET 6.x)" section.
61
62
- on -
64
65

minor edit (repetition)

---

Makefile

Remove .pdf docs until they are updated and include README.md in release

---

rxtools/source/lib/fs.c

rxtools: fs: Initialize NAND when booting

---

lang/fr.json

Kinda annoyed me so did it, ikr useless pull request

French language fix

---

rxtools/source/features/downgradeapp.c

This resolves injecting FBI for me at least.  Otherwise it would just hang

downgradeapp.c - update 'fbi' to unicode

---

rxtools/source/features/NandDumper.c

There were some magic numbers that had definitions at the beginning of the source file, this replaces them with the defined names.

replaced magic numbers with defined values

---

README.md

The instructions about the N3DS keys were confusing.

More information about the N3DS keys.

---

rxtools/Makefile
rxtools/source/lib/draw.c

- CakesROP version updated (Windows build issue eliminated)
- small bug in draw.c fixed
- a bit faster font conversion with Imagemagick (does the same with two passes instead of three. Can't manage to make it one-pass though.)

CakesROP updated

---

rxtools/source/features/screenshot.c

The function used to create wrong pictures.
Enable it because someone might need it (#414).

Fix & Enable screenshot
